// Generated by https://quicktype.io

import { Time } from '@angular/common';
import { Flight } from './flight.model';
import { Passenger } from './passenger.model';

export interface Reservation {
  reservationId: number;
  passenger: Passenger;
  flight: Flight;
  flyingDate: Date;
  flyingTime: Time;
  seatType: string;
  numOfSeats: number;
  confirmationNumber: string;
}
