// Generated by https://quicktype.io

import { Flight } from './flight.model';
import { Passenger } from './passenger.model';
import { Reservation } from './reservation.model';

export interface JsonResponse {
  status: boolean;
  message: string;
  responseObject:
    | Flight
    | Flight[]
    | Passenger
    | Reservation[]
    | number
    | string;
}
